### ISSUE TITLE
Capitalization conventions

### ISSUE THREAD

**Issue by NMoskalev** [Vityuska98/Simple-Csharp-Calculator#3]
Could you please pay attention to variable and class names, for example:
https://github.com/Vityuska98/Simple-Csharp-Calculator/blob/9958577e6837fe486c0fd65954439b368225f021/Program.cs#L24

Please follow to [this guide](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)

**Comment by Vityuska98** [comment]
Completed
