### ISSUE TITLE
Format source code

### ISSUE THREAD

**Issue by NMoskalev** [Vityuska98/Simple-Csharp-Calculator#5]
https://github.com/Vityuska98/Simple-Csharp-Calculator/blob/9958577e6837fe486c0fd65954439b368225f021/Program.cs#L23

Could you please format your source code using [this article](https://mkyong.com/vscode/how-to-format-source-code-in-visual-studio-code-vscode/) ?

**Comment by Vityuska98** [comment]
Completed
